### PR TITLE
Swap env task

### PR DESCRIPTION
**Pull request by csokol**
@lcguerrerocovo @pedrolis 

I created a new task to swap urls of running environments. 

The idea is that you specify the url and the environment that you want to place in this url, for example:

```
gradle swapEnvironmentUrl -PtargetUrl=production-app.elasticbeanstalk.com -PnewEnvironment=latestVersionEnvironmentName
```

This will swap the app running in production-app.elasticbeanstalk.com with the one named latestVersionEnvironmentName.

### CODE REVIEW

**Comment by pedrolis** [comment]
:+1: We just need to test :)

**Comment by lcguerrerocovo** [comment]
looks good

**Comment by lcguerrerocovo** [comment]
@csokol it would be nice to add some documentation on the project wiki on how to run the tasks just like you did here in the pr

**Comment by csokol** [comment]
I started our docs and linked it in the project's readme: https://github.com/VivaReal/gradle-plugins/wiki/Tasks :-)

**Pull request merged**
