### PR TITLE
setting default instance shutdown behavior as terminate

### PR DESCRIPTION
**Pull request by lcguerrerocovo**
@cairesvs

### CODE REVIEW

**Comment by pedrolis** [comment]
@lcguerrerocovo I think it should be better let the default value as actually is (I suppose that the default value is `stop`), and if the project has a specific parameter we can override that behavior. I don't know if there is someone else using this plugin.

**Comment by cairesvs** [comment]
It would be nice if we could override it but as @pedrolis said it I don't know who is using right now so this could be a improvement.

**Comment by ericzumba** [comment]
@lcguerrerocovo @cairesvs @pedrolis I'm sorry, but I'm missing the context of this change so I'm not sure what it is meant to fix or improve. Could you please provide me with the context? 
It seems to me that in some cases I'd rather have the instance just stopped. Mainly when they fail (or are deliberately shutdown by the ELB) and we end up unable to figure out what happened.

**Comment by lcguerrerocovo** [comment]
I think we should take care of gracefully shutting down instances in a way
that we stream or push all log information for analysis purposes. If not
then we'll always have stopped instances lying around and will always
require manual intervention to terminate them. I think you guys are right
in That we probably aren't ready for this change so I won't merge it in but
I think we should move in this general direction in the future.

**Comment by lcguerrerocovo** [comment]
@pedrolis you are definitely right for a moment I forgot there could be
other people finding this plugin useful. :)

**Pull request closed without merging**
